# litellm_config.yaml
# This file defines the models, routing, and access control for your LLM gateway.

# ----------------------------------------------------------------------------------
# General Proxy Settings
# ----------------------------------------------------------------------------------
general_settings:
  master_key: "os.environ/LITELLM_MASTER_KEY"
  database_url: "os.environ/DATABASE_URL"
  database_connection_pool_limit: 20
  store_model_in_db: true
  store_prompts_in_spend_logs: true

# ----------------------------------------------------------------------------------
# Router and Caching Settings
# ----------------------------------------------------------------------------------
router_settings:
  # FIX: Point to the Redis container using environment variables
  redis_host: "os.environ/REDIS_HOST"
  redis_password: "os.environ/REDIS_PASSWORD"
  redis_port: "os.environ/REDIS_PORT"

  routing_strategy: latency-based-routing
  allowed_fails: 3
  cooldown_time: 60
  num_retries: 2
  timeout: 600

# ----------------------------------------------------------------------------------
# LiteLLM Core Settings
# ----------------------------------------------------------------------------------
litellm_settings:
  set_verbose: False
  drop_params: True

# ----------------------------------------------------------------------------------
# Model List & Access Control
# ----------------------------------------------------------------------------------
model_list:
  # UIGEN-FX-SMALL Model
  - model_name: "UIGEN-FX-SMALL"
    litellm_params:
      model: "openai/uigen-fx-4b-intermediate"
      api_base: "http://129.212.184.243/v1"
      api_key: "randomapikey"
    model_info:
      access_groups: [ "free" ]
      rpm_limit: 500
      tpm_limit: 100000

  # WEBGEN-SMALL Model
  - model_name: "WEBGEN-SMALL"
    litellm_params:
      model: "openai/webgen-44k-550"
      api_base: "http://129.212.184.118/v1"
      api_key: "randomapikey"
    model_info:
      access_groups: [ "free" ]
      rpm_limit: 500
      tpm_limit: 100000
