name: Deploy to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  BASE_URL: https://designer.tesslate.com
  NEXT_PUBLIC_BASE_URL: https://designer.tesslate.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Build and push Docker image
      run: |
        docker build . \
          --build-arg POSTGRES_URL="${{ secrets.POSTGRES_URL }}" \
          --build-arg FIREBASE_SERVICE_ACCOUNT='${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' \
          --build-arg STRIPE_SECRET_KEY="${{ secrets.STRIPE_SECRET_KEY }}" \
          --build-arg STRIPE_WEBHOOK_SECRET="${{ secrets.STRIPE_WEBHOOK_SECRET }}" \
          --build-arg STRIPE_PLUS_PRICE_ID="${{ secrets.STRIPE_PLUS_PRICE_ID }}" \
          --build-arg STRIPE_PRO_PRICE_ID="${{ secrets.STRIPE_PRO_PRICE_ID }}" \
          --build-arg BASE_URL="${{ secrets.BASE_URL }}" \
          --build-arg NEXT_PUBLIC_BASE_URL="${{ secrets.NEXT_PUBLIC_BASE_URL }}" \
          --build-arg NEXT_PUBLIC_FIREBASE_API_KEY="${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}" \
          --build-arg NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}" \
          --build-arg NEXT_PUBLIC_FIREBASE_PROJECT_ID="${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}" \
          --build-arg NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}" \
          --build-arg NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}" \
          --build-arg NEXT_PUBLIC_FIREBASE_APP_ID="${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}" \
          --build-arg LITELLM_MASTER_KEY="${{ secrets.LITELLM_MASTER_KEY }}" \
          -t ${{ secrets.ACR_LOGIN_SERVER }}/tesslate-designer:${{ github.sha }} \
          -t ${{ secrets.ACR_LOGIN_SERVER }}/tesslate-designer:latest
        
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/tesslate-designer:${{ github.sha }}
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/tesslate-designer:latest
    
    - name: Update Container App
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az containerapp update \
            --name tesslate-designer \
            --resource-group designer-rg \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/tesslate-designer:${{ github.sha }} \
            --set-env-vars \
              "NODE_ENV=production" \
              "BASE_URL=${{ secrets.BASE_URL }}" \
              "NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }}" \
              "POSTGRES_URL=${{ secrets.POSTGRES_URL }}" \
              "FIREBASE_SERVICE_ACCOUNT=${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" \
              "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" \
              "STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}" \
              "STRIPE_PLUS_PRICE_ID=${{ secrets.STRIPE_PLUS_PRICE_ID }}" \
              "STRIPE_PRO_PRICE_ID=${{ secrets.STRIPE_PRO_PRICE_ID }}" \
              "LITELLM_MASTER_KEY=${{ secrets.LITELLM_MASTER_KEY }}" \
              "AUTH_SECRET=${{ secrets.AUTH_SECRET }}" \
              "NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}" \
              "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}" \
              "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}" \
              "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}" \
              "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}" \
              "NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}"
          
          echo "Deployment complete!"
          echo "URL: https://$(az containerapp show --name tesslate-designer --resource-group designer-rg --query properties.configuration.ingress.fqdn -o tsv)"