name: Deploy to Production VPS

on:
  push:
    branches: [main]  # Deploy when pushing to main branch
  workflow_dispatch:  # Allow manual deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
        
    - name: Add VPS to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
        
    - name: Deploy to VPS
      env:
        VPS_HOST: ${{ secrets.VPS_HOST }}
        VPS_USER: ${{ secrets.VPS_USER }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      run: |
        ssh $VPS_USER@$VPS_HOST << 'EOF'
          set -e
          
          # Navigate to deployment directory
          cd ${{ secrets.DEPLOY_PATH }}
          
          # Pull latest changes
          git pull origin main
          
          # Load environment variables
          export $(cat .env | grep -v '^#' | xargs)
          
          # Build and restart services
          docker-compose -f docker-compose.yml -f docker-compose.production.yml down
          docker-compose -f docker-compose.yml -f docker-compose.production.yml build --no-cache
          docker-compose -f docker-compose.yml -f docker-compose.production.yml up -d
          
          # Wait for services to be healthy
          echo "Waiting for services to start..."
          sleep 30
          
          # Verify deployment
          docker-compose ps
          
          # Test health endpoints
          curl -f http://localhost:3000/api/health || echo "Main app health check failed"
          curl -f http://localhost:4000/health || echo "LiteLLM health check failed"
          
          echo "Deployment completed successfully!"
        EOF