name: Security & Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Snyk on dependencies
        uses: snyk/actions/node@v3
        with:
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Build Docker image
        run: docker build -t studio-lite:latest .

      - name: Run Snyk on Docker image
        uses: snyk/actions/docker@v3
        with:
          image: studio-lite:latest
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} 